spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      jdbc-url: jdbc:h2:mem:elog;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE

  redis:
    host: localhost
    port: 26370
    database: 0